- name: "siteConfig"
  label: "Configuration du site"
  files:
    - file: "src/content/config/site-config.yml"
      name: "site-config"
      label: "Paramètres généraux"
      i18n:
        structure: single_file
      fields:
        - label: "Visibilité des sections"
          name: "sectionsVisibility"
          widget: "object"
          fields:
            - label: "Section Articles"
              name: "articlesSection"
              widget: "boolean"
              default: false
              hint: "Activer ou désactiver l'affichage de la section Articles sur la page d'accueil et dans la navigation"
    