[[redirects]]
  from = "/"
  to = "/fr"
  status = 302
  force = true

[build.processing]
  skip_processing = false
[build.processing.images]
  compress = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"