[[redirects]]
  from = "/"
  to = "/fr"
  status = 302
  force = true

[build.processing]
  skip_processing = false
[build.processing.images]
  compress = true

# Configuration d'indexation simple et universelle - sans condition qui pourrait mal fonctionner
[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "index, follow, all"