backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/images"
public_folder: "/assets/images"

i18n:
  structure: multiple_folders
  locales: [fr, en, it]
  default_locale: fr

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    i18n: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Read Time", name: "readTime", widget: "string" }
      - { label: "Categories", name: "categories", widget: "list" }
      - { label: "Highlights", name: "highlights", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }

  - name: "home"
    label: "Page d'accueil"
    files:
      - file: "src/content/home/home.yml"
        name: "home"
        label: "Contenu de la page d'accueil"
        i18n:
          structure: single_file
        fields:
          - label: "Français"
            name: "fr"
            widget: "object"
            fields: &homeFields
              - label: "Hero Section"
                name: "hero"
                widget: "object"
                fields:
                  - {label: "Titre", name: "title", widget: "string"}
                  - {label: "Sous-titre", name: "subtitle", widget: "string"}
                  - {label: "Description", name: "description", widget: "text"}
                  - {label: "Texte du bouton CTA", name: "cta", widget: "string"}
              - label: "Section Expertise"
                name: "expertise"
                widget: "object"
                fields:
                  - {label: "Titre", name: "title", widget: "string"}
                  - {label: "Description", name: "description", widget: "text"}
              - label: "Section Travailleurs"
                name: "travailleurs"
                widget: "object"
                fields:
                  - {label: "Titre", name: "title", widget: "string"}
                  - {label: "Description", name: "description", widget: "text"}
                  - {label: "Texte du bouton CTA", name: "cta", widget: "string"}
              - label: "Section Employeurs"
                name: "employeurs"
                widget: "object"
                fields:
                  - {label: "Titre", name: "title", widget: "string"}
                  - {label: "Description", name: "description", widget: "text"}
                  - {label: "Texte du bouton CTA", name: "cta", widget: "string"}
              - label: "Section Profil"
                name: "profil"
                widget: "object"
                fields:
                  - {label: "Titre", name: "title", widget: "string"}
                  - {label: "Description", name: "description", widget: "text"}
              - label: "Section Honoraires"
                name: "honoraires"
                widget: "object"
                fields:
                  - {label: "Titre", name: "title", widget: "string"}
                  - label: "Liste des points clés"
                    name: "list"
                    widget: "list"
                    field: {label: Point, name: point, widget: string}
                  - {label: "Texte du bouton CTA", name: "cta", widget: "string"}
              - {label: "Titre de la section Articles", name: "articlesTitle", widget: "string"}
          - label: "English"
            name: "en"
            widget: "object"
            fields: *homeFields
          - label: "Italiano"
            name: "it"
            widget: "object"
            fields: *homeFields

  - name: "travailleurs"
    label: "Page Travailleurs"
    files:
      - file: "src/content/travailleurs/travailleurs.yml"
        name: "travailleurs"
        label: "Contenu de la page Travailleurs"
        i18n:
          structure: single_file
        fields:
          - label: "Français"
            name: "fr"
            widget: "object"
            fields: &travailleursFields
              - {label: "Titre", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - label: "Questions"
                name: "questions"
                widget: "list"
                field: {label: Question, name: question, widget: "string"}
              - {label: "Focus spécial", name: "specialFocus", widget: "string"}
              - label: "Points de focus"
                name: "focusPoints"
                widget: "list"
                field: {label: Point, name: point, widget: "string"}
              - {label: "Titre des services", name: "servicesTitle", widget: "string"}
              - label: "Services"
                name: "services"
                widget: "list"
                fields:
                  - {label: "Icône", name: "icon", widget: "select", options: ["Briefcase", "Shield", "FileText"]}
                  - {label: "Texte", name: "text", widget: "string"}
          - label: "English"
            name: "en"
            widget: "object"
            fields: *travailleursFields
          - label: "Italiano"
            name: "it"
            widget: "object"
            fields: *travailleursFields

  - name: "employeurs"
    label: "Page Employeurs"
    files:
      - file: "src/content/employeurs/employeurs.yml"
        name: "employeurs"
        label: "Contenu de la page Employeurs"
        i18n:
          structure: single_file
        fields:
          - label: "Français"
            name: "fr"
            widget: "object"
            fields: &employeursFields
              - {label: "Titre", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - label: "Questions"
                name: "questions"
                widget: "list"
                field: {label: Question, name: question, widget: "string"}
              - {label: "Conclusion", name: "conclusion", widget: "text"}
              - {label: "Titre des prestations", name: "servicesTitle", widget: "string"}
              - label: "Prestations"
                name: "services"
                widget: "list"
                fields:
                  - {label: "Icône", name: "icon", widget: "select", options: ["FileText", "UserPlus", "Shield", "Search"]}
                  - {label: "Texte", name: "text", widget: "string"}
          - label: "English"
            name: "en"
            widget: "object"
            fields: *employeursFields
          - label: "Italiano"
            name: "it"
            widget: "object"
            fields: *employeursFields

  - name: "profile"
    label: "Profil"
    files:
      - file: "src/content/profile/profile.yml"
        name: "profile"
        label: "Contenu du profil"
        i18n:
          structure: single_file
        fields:
          - label: "Français"
            name: "fr"
            widget: "object"
            fields: &profileFields
              - {label: "Nom", name: "name", widget: "string"}
              - {label: "Titre", name: "title", widget: "string"}
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Biographie", name: "bio", widget: "text"}
              - label: "Spécialités"
                name: "specialties"
                widget: "list"
              - label: "Langues"
                name: "languages"
                widget: "list"
                fields:
                  - {label: "Nom", name: "name", widget: "string"}
                  - {label: "Niveau", name: "level", widget: "string"}
              - label: "Parcours"
                name: "careerPath"
                widget: "list"
                fields:
                  - {label: "Année", name: "year", widget: "string"}
                  - {label: "Événement", name: "event", widget: "string"}
              - label: "Conférences"
                name: "conferences"
                widget: "list"
                fields:
                  - {label: "Date", name: "date", widget: "string"}
                  - {label: "Titre", name: "title", widget: "string"}
                  - {label: "Événement", name: "event", widget: "string"}
                  - {label: "Co-intervenants", name: "coSpeakers", widget: "list"}
              - label: "Publications"
                name: "publications"
                widget: "list"
                fields:
                  - {label: "Date", name: "date", widget: "string"}
                  - {label: "Titre", name: "title", widget: "string"}
                  - {label: "Éditeur", name: "publisher", widget: "string"}
                  - {label: "Co-auteurs", name: "coAuthors", widget: "list"}
          - label: "English"
            name: "en"
            widget: "object"
            fields: *profileFields
          - label: "Italiano"
            name: "it"
            widget: "object"
            fields: *profileFields

  - name: "legal"
    label: "Mentions légales"
    files:
      - file: "src/content/legal/legal.yml"
        name: "legal"
        label: "Contenu des mentions légales"
        i18n:
          structure: single_file
        fields:
          - label: "Français"
            name: "fr"
            widget: "object"
            fields: &legalFields
              - {label: "Titre", name: "title", widget: "string"}
              - {label: "Contenu", name: "content", widget: "markdown"}
          - label: "English"
            name: "en"
            widget: "object"
            fields: *legalFields
          - label: "Italiano"
            name: "it"
            widget: "object"
            fields: *legalFields

  - name: "privacy"
    label: "Politique de confidentialité"
    files:
      - file: "src/content/privacy/privacy.yml"
        name: "privacy"
        label: "Contenu de la politique de confidentialité"
        i18n:
          structure: single_file
        fields:
          - label: "Français"
            name: "fr"
            widget: "object"
            fields: &privacyFields
              - {label: "Titre", name: "title", widget: "string"}
              - {label: "Contenu", name: "content", widget: "markdown"}
          - label: "English"
            name: "en"
            widget: "object"
            fields: *privacyFields
          - label: "Italiano"
            name: "it"
            widget: "object"
            fields: *privacyFields

  - name: "honoraires"
    label: "Honoraires"
    folder: "src/content/honoraires"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - label: "Tarifs"
        name: "tarifs"
        widget: "object"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Travailleur", name: "travailleur", widget: "string"}
          - {label: "Employeur", name: "employeur", widget: "string"}
      - label: "Transparence"
        name: "transparence"
        widget: "object"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Points", name: "points", widget: "list"}
      - label: "Prévisibilité"
        name: "previsibilite"
        widget: "object"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Content", name: "content", widget: "text"}
          - {label: "Points", name: "points", widget: "list"}
      - label: "Assurance"
        name: "assurance"
        widget: "object"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Content", name: "content", widget: "text"}
      - label: "Video"
        name: "video"
        widget: "object"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "URL", name: "url", widget: "string"}