backend:
  name: proxy
  proxy_url: http://localhost:8081/api/v1
  branch: v6 # Branch to update

media_folder: "public/assets/images"
public_folder: "/assets/images"

# Copy the rest of your collections from config.yml here
# Or you can just include the original config
local_backend: true 