backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/images"
public_folder: "/assets/images"

collections:
  - name: "blog_fr"
    label: "Blog (FR)"
    folder: "src/content/blog_fr"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Read Time", name: "readTime", widget: "string" }
      - { label: "Categories", name: "categories", widget: "list" }
      - { label: "Highlights", name: "highlights", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      
  - name: "blog_it"
    label: "Blog (IT)"
    folder: "src/content/blog_it"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Read Time", name: "readTime", widget: "string" }
      - { label: "Categories", name: "categories", widget: "list" }
      - { label: "Highlights", name: "highlights", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "blog_en"
    label: "Blog (EN)"
    folder: "src/content/blog_en"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Read Time", name: "readTime", widget: "string" }
      - { label: "Categories", name: "categories", widget: "list" }
      - { label: "Highlights", name: "highlights", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }