backend:
  name: git-gateway
  branch: v6

media_folder: "public/assets/images"
public_folder: "/assets/images"

# Import des collections depuis des fichiers séparés
collections:
  - import: collections/site-config.yml
  - import: collections/blog.yml
  - import: collections/home.yml
  - import: collections/services.yml
  - import: collections/profile.yml
  - import: collections/legal.yml
  - import: collections/honoraires.yml 