sectionsVisibility: false
showContactForm: true
allowIndexing: true
lawyers:
  - name: "Christine Rizzo"
    phone: "+32 488 40 45 49"
    whatsapp: "32488404549"
    email: "christine@rizzoavocate.be"
    linkedin: "https://www.linkedin.com/in/chrizzo11/"
    calendarLink: "https://cal.com/c.rizzo-avocat.be/rendez-vous?duration=15"
  - name: "Stephanie Michiels"
    phone: "+32 498 50 29 01"
    whatsapp: "32498502901"
    email: "stephanie@michielsavocate.be"
    linkedin: "https://www.linkedin.com/in/stephanie-michiels-/"
    calendarLink: "https://cal.com/stephanie-michiels-v76dvl"
address: "Chaussée de Waterloo 1151, 1180 Bruxelles"
copyrightText: "C. Rizzo & S. Michiels"
seo:
  siteUrl: "https://crizzo-avocate.be"
  siteName: "Christine Rizzo - Avocate"
  siteDescription: "Christine Rizzo - Avocate en droit du travail à Bruxelles. Expertise pour employeurs et travailleurs."
  defaultSocialImage: "/default-social-image.jpg"
  favicon: "/favicon.ico"
  faviconPng32: "/favicon-32x32.png"
  faviconPng16: "/favicon-16x16.png"
  appleTouchIcon: "/apple-touch-icon.png"