sectionsVisibility: false
showContactForm: true
allowIndexing: true
lawyers:
  - phone: +32 488 40 45 49
    whatsapp: '32488404549'
    email: christine@rizzoavocate.be
    calendarLink: https://cal.com/c.rizzo-avocat.be/rendez-vous?duration=15
    id: christine-rizzo
  - phone: +32 498 50 29 01
    whatsapp: '32498502901'
    email: stephanie@michielsavocate.be
    calendarLink: https://cal.com/stephanie-michiels-v76dvl
    id: stephanie-michiels
  - id: arnaud-vanderhoeven-jacobs
    phone: +32 498 79 73 56
    email: ''
    calendarLink: https://cal.com/arnaudvanderhoeven
  - id: romain-archalaus
    phone: +32 495 69 31 91
    email: ''
    calendarLink: ''
contactIllustration: /assets/images/illustration_cta_2.svg
cabinetEmail: info@rizzo-michiels.be
address: Chaussée de Waterloo 1151, 1180 Bruxelles
copyrightText: C. Rizzo & S. Michiels
seo:
  siteUrl: https://rizzo-michiels.be
  siteName: Christine Rizzo & Stephanie Michiels - Avocates en droit du travail
  siteDescription: >-
    Christine Rizzo & Stephanie Michiels - Avocates en droit du travail à Bruxelles. Expertise pour
    employeurs et travailleurs.
  defaultSocialImage: /default-social-image.jpg
  favicon: /favicon.ico
  faviconPng32: /favicon-32x32.png
  faviconPng16: /favicon-16x16.png
  appleTouchIcon: /apple-touch-icon.png
team:
  - id: christine-rizzo
    slug: christine-rizzo
    name: Christine Rizzo
    image: /assets/images/christine-optimized.webp
    profileImage: /assets/images/christine-optimized.webp
    linkedin: https://www.linkedin.com/in/chrizzo11/
  - id: stephanie-michiels
    slug: stephanie-michiels
    name: Stephanie Michiels
    image: /assets/images/smichiels-optimized.webp
    profileImage: /assets/images/smichiels-portrait.webp
    linkedin: https://www.linkedin.com/in/stephanie-michiels-/
  - id: arnaud-vanderhoeven-jacobs
    slug: arnaud-vanderhoeven-jacobs
    name: Arnaud Vanderhoeven Jacobs
    image: /assets/images/team-placeholder.svg
    linkedin: https://www.linkedin.com/in/arnaud-vanderhoeven-jacobs-a21a84b8/
  - id: romain-archalaus
    slug: romain-archalaus
    name: Romain Archalaüs
    image: /assets/images/team-placeholder.svg
    linkedin: https://www.linkedin.com/in/romain-archala%C3%BCs/
